import {writable} from "svelte/store";

export const musicList = writable ([
	// {
	// 	id:"1",
	// 	image:"Lover.webp",
	// 	audio:"Lover.wav",
	// 	name:"Lover",
	// 	artist:"Cherrydee",
	// 	genre: "Afrobeat",
	// 	bpm: "100",
	// 	key: "Cm",
	// 	tag: [" Wizkid", " Skepta",]
	// },	
	{
		id:2,
		image:"Trench.webp",
		audio:"Trench.mp3",
		name:"Trench",
		artist:"Cherrydee",
		genre: "Afrobeat",
		bpm: "106",
		key: "Cm",
		tag: [" Wizkid", " Skepta",],
		price: "2000",
		quantity: 1,
	},
	{
		id:3,
		image:"Emotions.webp",
		audio:"Emotions.mp3",
		name:"Emotions",
		artist:"Cherrydee",
		genre: "Afrobeat",
		bpm: "100",
		tag: ["Rema", "Wizkid",],
		price: "100",
		quantity: 1,
	},
	{
		id:4,
		image:"Summer.webp",
		audio:"Summer.mp3",
		name:"Summer",
		artist:"Cherrydee",
		genre: "Afrobeat",
		bpm: "100",
		tag: ["Wizkid", "Tems"],
		price: "280",
		quantity: 1,
	},
	{
		id:5,
		image:"OverThem.webp",
		audio:"OverThem.mp3",
		name:"Over Them",
		artist:"Cherrydee",
		genre: "Afrobeat",
		bpm: "106",
		tag: ["Wizkid", "CKay"],
		price: "700",
		quantity: 1,
	},	
	{
		id:6,
		image:"Special.webp",
		audio:"Special.mp3",
		name:"Special",
		artist:"Cherrydee",
		genre: "Afrobeat",
		bpm: "103",
		tag: ["Kida Kudz", "Wizkid",],
		price: "200",
		quantity: 1,
	},
	{
		id:7,
		image:"WestSide.webp",
		audio:"Westside.mp3",
		name:"West Side",
		artist:"Cherrydee",
		genre: "Afrobeat",
		bpm: "101",
		tag: ["Asake", " Wizkid",],
		price: "400",
		quantity: 1,
	},
]
);